### ISSUE TITLE
Windows claims to detect a trojan

### ISSUE THREAD

**Issue by tofferlicious** [Astropilot/ValheimTooler#34]
I ran ValheimToolerLauncher.exe and updated to 1.9.1.
Then installed it, launched Valheim and then launched the Tooler.
Overlay is shown in Valheim, but Windows gave me a warning on the file
ValheimTooler_1.9.0\ValheimToolerLauncher.exe
 and calls the threat "Trojan:Win32/Bearfoos.A!ml"

It is under quarantaine now.
Anyone else experiencing this?

**Comment by Astropilot** [comment]
Hi @tofferlicious ,

Yes my launcher is detected as a virus by most of AntiVirus, see this report: https://www.virustotal.com/gui/file/b552f8cea2acbb9cb4496742c5f4d88cfd3c84ff106db3ac38b1f4324bfd2110/detection
The reason is legitimate, since one of the purposes of my launcher is to force the game to execute code that comes from an unofficial external source. From a technical point of view, this technique is called [DLL Injection](https://en.wikipedia.org/wiki/DLL_injection). As this technique can also be used for malicious purposes, antivirus software automatically detects it and lists my software as malicious.
Unfortunately, there's not much I can do about it. The best to do is define an exception on my tool in the antivirus.

Kind regards,
Astropilot

**Comment by tofferlicious** [comment]
Hi @Astropilot, 
thank you very much for the fast answer and in general for this great tool!
Will close the ticket, thanks again!
