### ISSUE TITLE
Ghost mode and invisibility

### ISSUE THREAD

**Issue by AntonioMertz** [Astropilot/ValheimTooler#38]
When in Ghost mode, the user is visible to other players via teleportation or health replenishment selections. For the server administrator, this is critical in maintaining law and order. Is it possible to remove the ability to display the names of players who are near you in Ghost mode? Thanks

**Comment by Astropilot** [comment]
Hi @AntonioMertz ,

The ghost mode feature is actually an already defined feature in the game that my tool is only giving to the user without needing dev console/commands. This feature has been developed by the game devs to only be invisible to monsters, not players.
To be able to implement this feature, it would require to develop a mod to be installed on the server (because the client alone cannot do it), that is out of scope of this project.

Kind regards,
Astropilot

**Comment by AntonioMertz** [comment]
Thanks for the answer. I mean hiding the player name in Ghost is in your program. So that he is not visible in the list for teleporting or replenishing health for other players if he is in Ghost mode

**Comment by AntonioMertz** [comment]
Thanks for the answer and good luck
