### ISSUE TITLE
Turning on god, ghost, or infinite self stamina breaks building range

### ISSUE THREAD

**Issue by Drudicta** [Astropilot/ValheimTooler#45]
If I activate any of these three options, I can only build up to about 2 meters in front of me afterward, even if I shut them off. I have to close and reopen the game to fix the problem.
![image](https://github.com/user-attachments/assets/a3a7896d-275a-48c9-b0e0-000a1efb3c40)
![image](https://github.com/user-attachments/assets/bd47a846-28fe-40cb-a48f-e5e149d136d6)
![image](https://github.com/user-attachments/assets/3c8cd942-a912-48fd-b3e6-96b331e74517)

**Comment by G234i** [comment]
Same issue here, interferes with "Build Camera - Vapok" as it relies on custom extended build range

**Comment by Astropilot** [comment]
Hi there,
This is very strange as my tool does very minimal modifications to the game, for GodMode for example, it only use what the game already provide internally.
This is certainly a issue of mod compatibility but I can't do anything about that, it is not possible to handle how all the other mods works :/
Kind regards,
Astropilot

**Comment by G234i** [comment]
Some new info after testing this is not mod conflict related.
Using BepInEx 5.4.22.0 with just ValheimTooler 1.10.0.

On startup in the main menu inside ValheimTooler menu(VTmenu for short) the "Interaction distance" is set to 5f.
Upon joining a world and opening the VTmenu "Interaction distance" is changed and shows 3.5f  (opening the mod menu is what seems to cause the update of the value for the player (maybe Player.m_localPlayer.m_maxInteractDistance  ??))

After some experimenting it would seem that the default "vanilla" value for the interact distance is somewhere between 7.8f-8f.
Looking at the source code I cannot pinpoint where exactly the Player.m_localPlayer.m_maxInteractDistance gets set to 3.5f but its a one time thing as subsequent opening/closing of the VTmenu do not alter the interact distance.

On a side note about mod compatibility - Configuration Manager by aedenthorn breaks the BepInEx version of ValheimTooler  completely - maybe it should be listed in the readme.

**Comment by Astropilot** [comment]
Hi there,

Sorry for the long update.
Concerning the interaction/placement distance, the default in the game is 5
![image](https://github.com/user-attachments/assets/3b0c68e0-a863-430e-b2d1-b99a8c49bd9f)
If it is changed by any other mod, it may conflict with my mod as I read the value and update it for each frame when the mod menu is open. I will try to see what I can do to prevent this incompatibility, otherwise I may remove this feature.

About Configuration Manager by aedenthorn, it hasn't been updated since April 2021, so except many other mods to not work with it, I recommend an more updated one like: https://thunderstore.io/c/valheim/p/Azumatt/Official_BepInEx_ConfigurationManager/

**Comment by Astropilot** [comment]
I removed the "far interaction distance" feature in the last update (v1.11.0) for the time being. If I find a way to make it works without breaking compatibility with other mods I will add it again.
I'm closing the issue, if you still having this problem don't hesitate to tell me!
