### ISSUE TITLE
Weight feature is not working.

### ISSUE THREAD

**Issue by Kirbyarm** [Astropilot/ValheimTooler#46]
The infinite inventory weight toggle doesn't appear to do anything.

I still get encumbered when I carry too much and both the carried weight and carry weight capacity values appear to be unchanged when the feature is activated.

**Comment by Astropilot** [comment]
Hi,

Do you use the modded version or the standalone (launcher) version? If it is the former do you use other mods beside ValheimTooler?

Kind regards,
Astropilot

**Comment by Kirbyarm** [comment]
Hello,

Love this tool, it's SUPER awesome!

No other mods whatsoever. Just playing on a friend's local world with a group.

Using the non-Bepix version of the ValheimTooler.

Latest Steam version of Valheim. I click Play from Library and choose the non-Vulkan option when it pops up.

I do however tamper with the memory to freeze current weight at 0... but it's extremely buggy. The feature still doesn't work before I attach the memory tamperer though.

**Comment by Astropilot** [comment]
That's weird for sure! It is working properly on my side 😮 

See without the feature activated:
![image](https://github.com/user-attachments/assets/6709c4f6-3918-4c75-b71b-d139f6f5ca4b)

And with the feature activated:
![image](https://github.com/user-attachments/assets/1eebe860-568f-4d19-98fa-8864ff4ac041)

When pressing "Launch" on my launcher, do you do it only after the game main screen appears and not before?
Because if you "launch" it almost as soon as you pressed play on Steam, it may not be able to properly patch the game as it is still uninitialized:
![image](https://github.com/user-attachments/assets/a669d156-96fa-40f4-8ad8-3dd3d4ca024b)

Kind regards,
Astropilot

**Comment by Kirbyarm** [comment]
Thank you for checking and for the response!

Also, I understand about being in maintenance mode, apologies for not seeing that post. If I could program worth a damn I would be very interested in helping implement that. Sorry!

As soon as I have a moment, I will try doing it at that exact screen, but I believe I pressed the Launch button when I'm loaded into the game completely (I distinctly remember the DEL menu popping up as soon as I inject it)

**Comment by Kirbyarm** [comment]
Oh, I see. That's perfectly understandable and reasonable, thanks for allowing a section for people to post wanted features like that!

It looks like that did it! Injecting at the title screen seems to have made it work fine, at least in my test world. I'm confident it will also work fine with the group session later this week. Much obliged for your prompt assistance and explanations.

I will close this ticket now. :)
