### ISSUE TITLE
ValheimTooler as BepInEx Mod?

### ISSUE THREAD

**Issue by KillerGoldFisch** [Astropilot/ValheimTooler#5]
Hi @Astropilot,

first of all: Thanks for this awesome tool!

I was wondering why this isn't a Mod?

I tried loading the unmodified "ValheimTooler.dll" assembly using a BepInEx mod and it worked like a charm. No need to inject the dll. This would make it much more accessable and does not scare people away by requering them to give elevated privileges to a software the may not trust.

Here is my loader mod: https://github.com/KillerGoldFisch/ValheimToolerLoaderMod

Cheers!

**Comment by Astropilot** [comment]
Hi @KillerGoldFisch !

First of all, thank you for your consideration of this project 😄 

The main reason is simply that the community targeted by this tool is more the cheaters than the mods users. I'm not a mod user myself and although I've heard about BepInEx I was never interested in it.

On cheats forums, it's not uncommon to have to run programs with high privileges, and that's why I never asked myself about trusting my tool ^^

I did some research on BepInEx and its integration with Valheim as well as your code to package my DLL in a plugin and I see a lot of advantages:
- As you said, no need for elevated privileges
- I know that some users of my tool also use mods, providing them with a version of my tool as a mod would surely be easier for them to centralize everything via a Mod Manager.
- Packaging it as a mod would allow to post it on sites like thunderstore, which would make it easier to put it in production because users could update it directly from the Mod Manager in one click.
- Since "BepInExPack for Valheim" brings by itself the unstripped Unity DLLs in a way my launcher could completely disappear since its role is to install the unstripped DLLs, inject the tool and bring the updates.

I'm still willing to keep the current system, for those who don't want to install BepInEx just for this tool, but I'm not opposed to providing a version as a BepInEx plugin as well. From what I've seen of your code, it looks relatively simple to package and since I don't need to port all the code into the plugin, the additional development burden is very low.

If you agree, I will add a new project to my solution based on your code to allow the generation of the BepInEx plugin, and then I will post it on thunderstore and nexusmods.

Thanks again for your proposal! 👍 

Yours truly,
Astropilot

**Comment by KillerGoldFisch** [comment]
Yes, i completely agree. Since it did work without any modification of "ValheimTooler.dll", it would be a waste of opportunity not supporting both.

Distributing it additionally on the thunderstore and nexusmods would also give the well deserved recognition.

Feel free to use my code as you whish, thats why i made the repo! 😄

Since you are not into modding, they commonly get dirtibuted in a zip file with this structure:

```
Zip file/
├─ BepInEx/
│  ├─ plugins/
│  │  ├─ ValheimTooler/
│  │  │  ├─ ValheimToolerLoaderMod.dll
│  │  │  ├─ ValheimTooler.dll
│  │  │  ├─ INIFileParser.dll
├─ readme.txt
├─ licence.txt
```

Thanks for accepting my request!

Cheers!

**Comment by Astropilot** [comment]
Great news, the modded version of the tool is now available :)
Thanks to your code I could go relatively fast!

The mod is available on the following links:
- Thunderstore: https://valheim.thunderstore.io/package/Astropilot/ValheimTooler/
- NexusMods: https://www.nexusmods.com/valheim/mods/1224

The new project is present under the name `ValheimToolerMod` in the repository and I updated the credits to include you (well deserved!)

Thanks again and don't hesitate if you have other remarks.

Best regards,
Astropilot
