### ISSUE TITLE
Unity Error

### ISSUE THREAD

**Issue by srtzero** [Astropilot/ValheimTooler#7]
This error pops up each time I start the game.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ValheimTooler.UI.SpriteManager.TextureFromSprite (UnityEngine.Sprite sprite) (at <2f2ae1bfaad2402898dbfd0c43df3bd7>:0)
ValheimTooler.Core.ItemGiver.Start () (at <2f2ae1bfaad2402898dbfd0c43df3bd7>:0)
ValheimTooler.EntryPoint.Start () (at <2f2ae1bfaad2402898dbfd0c43df3bd7>:0)

As a follow up the error doesn't seem to prevent me from executing any commands. Everything seems to trigger when pressed or spawned. This error only pops up when the game first starts and BepInEx first loads all plugins.

**Comment by themaoci** [comment]
its your mods that are fking it up you should check mods that adding new items and are missing sprite icon of it

**Comment by Astropilot** [comment]
This issue was seen a long time ago on Discord, here is the answer I put at the time:

> It's seems to be related to the ItemGiver feature. When the plugin startup it will load all items especially their icons. And the error is corresponding to a problem to load some icon's item. Have you any other mod installed besides ValheimTooler? There is a good chance that the problem is caused by a mod adding an item to the game that my mod can't handle properly.
>
> -- <cite>Discord: [Astropilot], 11 October 2021</cite>

The problem occurs with mods that add new objects but don't use the associated sprites or use them badly. Unfortunately I can't do anything to make them compatible, the best I can do is to simply ignore them so they don't impact the Item Giver.
There will be no more exceptions generated for this case in the next update. Note that the error is not blocking, just useless and polluting.
